nome = str(input('Digiter seu nome completo: ')).strip()
print('Analisando seu nome...')
print(f'Seu nome em maiúsculas é {nome.upper()}')
print(f'Seu nome em minúsculas é {nome.lower()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")}')
separa = nome.slit()
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras')
